const DEFAULT_AI_PROFILE = {
  nickname: '',
  categories: [],
  emotionLevel: 0,
  emotionLabel: '',
  messagesCount: 0,
  activityLevel: 0,
  avatarUrl: null,
  status: '',
  statusColor: '#CCCCCC',
  favoriteEmoji: '',
  badges: [],
  activityLast7Days: [0,0,0,0,0,0,0],
  quote: '',
  emotionTimeline: [0,0,0,0,0,0,0],
  aiAdvice: '',
  aiProfileSummary: '',
  socialCircle: [],
  aiAchievements: [],
  aiHeadline: '',
  timeInApp: [0,0,0,0,0,0,0],
  aiStyle: '',
  aiCurrentMood: '',
  aiSupportScore: 0,
  lastOnline: '',
  online: false
};
