name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project to server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            rm -rf /chat/*
          EOF

          scp -r . root@${{ secrets.SERVER_IP }}:/chat/

      - name: Start app
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << EOF
            cd /chat

            # Write .env
            echo "DB_HOST=localhost" > .env
            echo "DB_USER=listik" >> .env
            echo "DB_PASSWORD=root" >> .env
            echo "DB_NAME=chat" >> .env
            echo "DB_DIALECT=postgres" >> .env
            echo "DB_PORT=5432" >> .env

            npm install

            # Start with pm2
            pm2 stop chat || true
            pm2 start npm --name chat -- run start
            pm2 save
          EOF
